=== veetech-ai/df-commons/schemas/automa-alerts.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "code": {
        "type": "number"
      },
      "name": {
        "type": "string",
        "enum": ["batteryCharging", "batteryCharged", "vbatAlert", "noCharging"]
      },
      "value": {
        "anyOf": [
          {
            "type": "number",
            "enum": [0, 1]
          },
          {
            "type": "boolean",
            "enum": [false, true]
          }
        ]
      },
      "category": {
        "type": "string",
        "enum": ["error", "warning", "info"]
      },
      "description": {
        "type": "string"
      }
    },
    "additionalProperties": false,
    "required": ["code", "name", "category"]
  }
}

=== veetech-ai/df-commons/data/automa-alerts.json
[
  {
    "code": 0,
    "name": "batteryCharging",
    "value": false,
    "category": "info",
    "description": "Battery Charging"
  },
  {
    "code": 1,
    "name": "batteryCharged",
    "value": false,
    "category": "info",
    "description": "Battery Charged"
  },
  {
    "code": 2,
    "name": "vbatAlert",
    "value": false,
    "category": "warning",
    "description": "Vbat Alert"
  },
  {
    "code": 3,
    "name": "noCharging",
    "value": false,
    "category": "error",
    "description": "No Charging"
  }
]
